var text01 = "Reset";
var text02 = ["Start", "Pauză", "Continuare"];  
var text03 = "Mișcare încetinită";
var text04 = "Constanta de";
var text04x = "elasticitate:";
var text05 = "Masa:";
var text06x = "Accelerația";
var text06 = "gravitațională:";
var text07 = "Amplitudinea:";
var text08 = "Elongația";
var text09 = "Viteza";
var text10 = "Accelerația";
var text11 = "Forța";
var text12 = "Energia";
var decimalSeparator = ",";
var newtonPerMeter = "N/m";                              
var kilogram = "kg";                                
var meterPerSecond2 = "m/s&sup2;";                
var meter = "m";
var text13 = "Maximum";
var text14 = "Elongația";
var text15 = "Viteza";
var text16 = "Accelerația";
var text17 = "Forța";
var text18 = "Energia potențială";
var text19 = "Energia cinetică";
var text20 = "Energia totală";
var text21 = "(în s)";
var text22 = "(în m)";
var text23 = "(în m/s)";
var text24 = "(în m/s\u00b2)";
var text25 = "(în N)";
var text26 = "(în J)";
var text27 = "Perioda de oscilație";
var symbolTime = "t";
var symbolElongation = "s";
var symbolVelocity = "v";
var symbolAcceleration = "a";
var symbolForce = "F";
var symbolEnergy = "E";
var symbolPotential = "p";
var symbolKinetic = "c";
var second = "s";                                     
var meterUnicode = "m";                              
var meterPerSecond = "m/s";                           
var meterPerSecond2Unicode = "m/s\u00b2";            
var newton = "N";                                    
var joule = "J";                                   
var textPhysics = "Fizica";
var textCollection = "Appleturi de fizica";
var colorBackground = "#bad4d2";
var colorClock1 = "#808080";
var colorClock2 = "#000000";
var colorClock3 = "#ff0000";
var colorElongation = "#ff0000";
var colorVelocity = "#ff00ff";  
var colorAcceleration = "#0000ff";
var colorForce = "#008020";
var colorBody = "#ffffff";
var FONT1 = "normal normal bold 12px cambria math";
var ax = 100, ay = 50;
var py0 = 180;
var xD = 220, yD1 = py0, yD2 = 160;
var tPix = 20;
var canvas, ctx;
var width, height;
var bu1, bu2;
var cbSlow;
var ipD, ipM, ipG, ipA;
var rbY, rbV, rbA, rbF, rbE;
var on;
var slow;
var t0;
var t;
var tU;
var timer;
var D;
var m;
var g;
var A;
var omega;
var T;
var phi, sinPhi, cosPhi;
var yPix;
var py;
var nrSize; 